columns:
"\uFEFFQTY_DOT_URL": int
QTY_HYPHEN_URL: int
QTY_UNDERLINE_URL: int
QTY_SLASH_URL: int
QTY_QUESTIONMARK_URL: int
QTY_EQUAL_URL: int
QTY_AT_URL: int
QTY_AND_URL: int
QTY_EXCLAMATION_URL: int
QTY_SPACE_URL: int
QTY_TILDE_URL: int
QTY_COMMA_URL: int
QTY_PLUS_URL: int
QTY_ASTERISK_URL: int
QTY_HASHTAG_URL: int
QTY_DOLLAR_URL: int
QTY_PERCENT_URL: int
QTY_TLD_URL: int
LENGTH_URL: int
QTY_DOT_DOMAIN: int
QTY_HYPHEN_DOMAIN: int
QTY_UNDERLINE_DOMAIN: int
QTY_SLASH_DOMAIN: int
QTY_QUESTIONMARK_DOMAIN: int
QTY_EQUAL_DOMAIN: int
QTY_AT_DOMAIN: int
QTY_AND_DOMAIN: int
QTY_EXCLAMATION_DOMAIN: int
QTY_SPACE_DOMAIN: int
QTY_TILDE_DOMAIN: int
QTY_COMMA_DOMAIN: int
QTY_PLUS_DOMAIN: int
QTY_ASTERISK_DOMAIN: int
QTY_HASHTAG_DOMAIN: int
QTY_DOLLAR_DOMAIN: int
QTY_PERCENT_DOMAIN: int
QTY_VOWELS_DOMAIN: int
DOMAIN_LENGTH: int
DOMAIN_IN_IP: int
SERVER_CLIENT_DOMAIN: int
QTY_DOT_DIRECTORY: int
QTY_HYPHEN_DIRECTORY: int
QTY_UNDERLINE_DIRECTORY: int
QTY_SLASH_DIRECTORY: int
QTY_QUESTIONMARK_DIRECTORY: int
QTY_EQUAL_DIRECTORY: int
QTY_AT_DIRECTORY: int
QTY_AND_DIRECTORY: int
QTY_EXCLAMATION_DIRECTORY: int
QTY_SPACE_DIRECTORY: int
QTY_TILDE_DIRECTORY: int
QTY_COMMA_DIRECTORY: int
QTY_PLUS_DIRECTORY: int
QTY_ASTERISK_DIRECTORY: int
QTY_HASHTAG_DIRECTORY: int
QTY_DOLLAR_DIRECTORY: int
QTY_PERCENT_DIRECTORY: int
DIRECTORY_LENGTH: int
QTY_DOT_FILE: int
QTY_HYPHEN_FILE: int
QTY_UNDERLINE_FILE: int
QTY_SLASH_FILE: int
QTY_QUESTIONMARK_FILE: int
QTY_EQUAL_FILE: int
QTY_AT_FILE: int
QTY_AND_FILE: int
QTY_EXCLAMATION_FILE: int
QTY_SPACE_FILE: int
QTY_TILDE_FILE: int
QTY_COMMA_FILE: int
QTY_PLUS_FILE: int
QTY_ASTERISK_FILE: int
QTY_HASHTAG_FILE: int
QTY_DOLLAR_FILE: int
QTY_PERCENT_FILE: int
FILE_LENGTH: int
QTY_DOT_PARAMS: int
QTY_HYPHEN_PARAMS: int
QTY_UNDERLINE_PARAMS: int
QTY_SLASH_PARAMS: int
QTY_QUESTIONMARK_PARAMS: int
QTY_EQUAL_PARAMS: int
QTY_AT_PARAMS: int
QTY_AND_PARAMS: int
QTY_EXCLAMATION_PARAMS: int
QTY_SPACE_PARAMS: int
QTY_TILDE_PARAMS: int
QTY_COMMA_PARAMS: int
QTY_PLUS_PARAMS: int
QTY_ASTERISK_PARAMS: int
QTY_HASHTAG_PARAMS: int
QTY_DOLLAR_PARAMS: int
QTY_PERCENT_PARAMS: int
PARAMS_LENGTH: int
TLD_PRESENT_PARAMS: int
QTY_PARAMS: int
EMAIL_IN_URL: int
TIME_RESPONSE: float
DOMAIN_SPF: int
ASN_IP: int
TIME_DOMAIN_ACTIVATION: int
TIME_DOMAIN_EXPIRATION: int
QTY_IP_RESOLVED: int
QTY_NAMESERVERS: int
QTY_MX_SERVERS: int
TTL_HOSTNAME: int
TLS_SSL_CERTIFICATE: int
QTY_REDIRECTS: int
URL_GOOGLE_INDEX: int
DOMAIN_GOOGLE_INDEX: int
URL_SHORTENED: int
RESULT: int
target_column: RESULT